spring:
  jackson:
   date-format: yyyy-MM-dd HH:mm:ss # ⽇期格式
   default-property-inclusion: NON_NULL # 不为null时序列化   只有不为null的项才进行返回
  application:
    name: 论坛系统
  output:
   ansi:
      enabled: always
#      配置数据库
  datasource:
   url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false
   username: root
   password: BITE@yyds.666
    #   password: BITE@yyds.666
   #数据库驱动
   driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss   #日志的时间格式
  level:
    root: info
#  file:
#    path: /log/forum_001          #生产环境的日志目录

# mybatis 相关配置，单独配置，顶格写     可以更好地集成Spring boot 和 mybatis   避免发生错误
mybatis:
 mapper-locations: classpath:mapper/**/*.xml # 指定 xxxMapper.xml的扫描路径   所有路径下的 .xml的文件
forum:
  login:
    url: sign-in.html
  index:
    board-num: 9

